name: bangla_ocr_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  tesseract_ocr: ^0.5.0
  image_picker: ^1.2.0
  path_provider: ^2.1.4
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/tessdata/
    - assets/icon/icon.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png

  android_12:
    image: assets/icon/icon.png
    color: "#ffffff"